apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
        env:
        - name: POSTGRES_URL
          value: {{ .Values.backend.postgresUrl }}
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.postgresSecretName }}
              key: postgres-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.postgresSecretName }}
              key: postgres-user
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        resources:
          requests:
            cpu: {{ .Values.backend.resources.requests.cpu }}
            memory: {{ .Values.backend.resources.requests.memory }}
          limits:
            cpu: {{ .Values.backend.resources.limits.cpu }}
            memory: {{ .Values.backend.resources.limits.memory }}

      volumes:
      - name: logs
        hostPath:
          path: /var/log/petclinic
          type: DirectoryOrCreate
