apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
spec:
  selector:
    app: cadvisor
  ports:
  - port: {{ .Values.cadvisor.port }}
    targetPort: {{.Values.cadvisor.targetPort }}
  type: ClusterIP