apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec: 
      containers:
      - name: grafana
        image: {{ .Values.grafana.image }}
        ports: 
        - containerPort: {{ .Values.grafana.containerPort }}
        resources:
          requests:
            cpu: {{ .Values.grafana.resources.requests.cpu }}
            memory: {{ .Values.grafana.resources.requests.memory }}
          limits:
            cpu: {{ .Values.grafana.resources.limits.cpu }}
            memory: {{ .Values.grafana.resources.limits.memory }}                  
        env: 
        - name: GF_SMTP_ENABLED
          value: {{ .Values.grafana.gfSmtpEnabled | quote}}
        - name: GF_SMTP_HOST
          value: {{ .Values.grafana.gfSmtpHost }}
        - name: GF_SMTP_USER
          value: {{ .Values.grafana.gfSmtpUser }}
        - name: GF_SMTP_PASSWORD
          value: {{ .Values.grafana.gfSmtpPassword }}
        - name: GF_SMTP_FROM_ADDRESS
          value: {{ .Values.grafana.gfSmtpFromAddress }}
        - name: GF_SMTP_FROM_NAME
          value: Grafana
          volumeMounts: 
          - name: grafana-storage
            mountPath: /var/lib/grafana
      volumes: 
      - name: grafana-storage
        persistentVolumeClaim: 
          claimName: grafana-pvc