apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
  - port: {{ .Values.grafana.port }}
    targetPort: {{ .Values.grafana.targetPort }}
  type: NodePort