apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: {{ .Values.loki.replicaCount }}
  selector:
    matchLabels:
      app: loki
  template: 
    metadata:
      labels:
        app: loki
    spec: 
      containers: 
        - name: loki 
          image: {{ .Values.loki.image }}
          ports: 
            - containerPort: {{ .Values.loki.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.loki.resources.requests.cpu }}
              memory: {{ .Values.loki.resources.requests.memory }}
            limits:
              cpu: {{ .Values.loki.resources.limits.cpu }}
              memory: {{ .Values.loki.resources.limits.memory }}          
  