apiVersion: v1 
kind: Service
metadata: 
  name: loki-service
spec: 
  selector: 
    app: loki 
  ports: 
  - port: {{ .Values.loki.port }}
    targetPort: {{ .Values.loki.targetPort }}
  type: ClusterIP