apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: prometheus 
spec: 
  replicas: {{ .Values.prometheus.replicaCount }}
  selector: 
    matchLabels:
      app: prometheus 
  template: 
    metadata: 
      labels:
        app: prometheus 
    spec: 
      containers: 
      - name: prometheus 
        image: {{ .Values.prometheus.image }}
        resources:
          requests:
            cpu: {{ .Values.prometheus.resources.requests.cpu }}
            memory: {{ .Values.prometheus.resources.requests.memory }}
          limits:
            cpu: {{ .Values.prometheus.resources.limits.cpu }}
            memory: {{ .Values.prometheus.resources.limits.memory }}          
        ports: 
        - containerPort: {{ .Values.prometheus.containerPort }}
        args: 
        - "--config.file=/etc/prometheus/prometheus.yml"
        volumeMounts: 
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes: 
      - name: prometheus-config
        configMap: 
          name: prometheus-config