apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
spec:
  replicas: {{ .Values.promtail.replicaCount }}
  selector:
    matchLabels:
      app: promtail
  template: 
    metadata:
      labels:
        app: promtail
    spec: 
      containers: 
        - name: promtail
          image: {{ .Values.promtail.image }}
          resources:
            requests:
              cpu: {{ .Values.promtail.resources.requests.cpu }}
              memory: {{ .Values.promtail.resources.requests.memory }}
            limits:
              cpu: {{ .Values.promtail.resources.limits.cpu }}
              memory: {{ .Values.promtail.resources.limits.memory }}                    
          args: 
          - "-config.file=/etc/promtail/promtail-config.yml"
          volumeMounts: 
          - name: promtail-config
            mountPath: /etc/promtail/promtail-config.yml
            subPath: promtail-config.yml
          - name: logs 
            mountPath: /var/log/petclinic
            readOnly: true
      volumes: 
      - name: promtail-config
        configMap: 
          name: promtail-config
      - name: logs 
        hostPath:
          path: /var/log/petclinic
          type: DirectoryOrCreate
 