apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ffijuljani1/petclinicbe:latest
        ports:
        - containerPort: 9966
        env:
        - name: POSTGRES_URL           
          value: jdbc:postgresql://db-service:5432/petclinic      
        - name: POSTGRES_PASS
          value: petclinic      
        - name: POSTGRES_USER
          value: petclinic

