server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: petclinic-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: petclinic
          service: petclinicbe
          env: prod
          __path__: /var/log/petclinic/app.log

    pipeline_stages:
      - regex:
          expression: '^(?P<level>[A-Z]+)\s+(?P<logger>[^\s]+)\s+-\s+(?P<message>.*)'
      - labels:
          level:
      - output:
          source: message